services:
  - type: web
    name: densyst
    plan: free
    region: oregon
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false